on:
  pull_request:
  push:
    branches:
      - main
#    targets:
#      - checks
#      - docs
#      - say-hi

x-python-version: &python-version "3.10"

jobs:
  #checks:
  #  needs:
  #    - flake8
  #    - pylint
  #    - pytest
  #    - pyright

  docs:
    paths:
      - README.md # runs if the readme changes
    extra-key: something # also runs if this changes
    runs-on: ubuntu-20.04
    steps:
      - echo building docs from readme

  say-hi:
    runs-on: ubuntu-20.04
    paths: []
    force: true # always runs if needed by another job or by targets
    steps:
      - echo HI

  poetry:
    cixx-uses: ./poetry-project.yml
    with:
      python-version: *python-version
      path: ./

  check-self:
    runs-on: ubuntu-20.04
    paths:
      - .ci++/
      - .github/workflows/
    needs:
      - ${{ jobs.poetry.outputs.build }}
    steps:
      - echo "Built at ${{ jobs.poetry.outputs.build.outputs.timestamp }}"
      - uses: actions/setup-python@v3
        with:
          python-version: *python-version
      - |
        pip install cixx --find-links dist/
        ci++ ".ci++/main.yml" ".github/workflows/main.yml.new"
        diff ".github/workflows/main.yml.new" ".github/workflows/main.yml"
